version: 2

jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - run:
          name: Building project
          command: echo "Dummy Build"
  deploy:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           filters:
             branches:
               only: master