version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1-browsers
      - image: circleci/postgres:9.6.5-alpine-ram

    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir test-reports

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U ".[dev,test]"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint with flake8
          command: |
            . venv/bin/activate
            # stop the build if there are Python syntax errors or undefined names
            flake8  ~/repo --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 ~/repo --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
    deploy:
      docker:
        - image: circleci/python:3.6.2-stretch-browsers
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           filters:
             branches:
               only: master
