# Generated by Django 2.2.6 on 2019-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetclass', models.CharField(choices=[('COMMODITIES', 'Commodities'), ('CRYPTO', 'Cryptocurrency'), ('EQUITIES', 'Equities'), ('FOREX', 'FOREX'), ('FIXED', 'Fixed Income')], max_length=5)),
                ('category', models.CharField(choices=[('Shrimp', 'Shrimp'), ('Tea', 'Tea'), ('Sugar', 'Sugar')], max_length=5)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioID', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
