# Generated by Django 2.2.6 on 2019-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetclass',
            field=models.CharField(choices=[('COMMODITIES', 'Commodities'), ('CRYPTO', 'Cryptocurrency'), ('EQUITIES', 'Equities'), ('FOREX', 'FOREX'), ('FIXED', 'Fixed Income')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Shrimp', 'Shrimp'), ('Tea', 'Tea'), ('Sugar', 'Sugar')], max_length=100),
        ),
    ]
