# Generated by Django 2.2.6 on 2019-11-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191102_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='portfolioID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
            preserve_default=False,
        ),
    ]
