# Generated by Django 2.2.6 on 2019-11-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_asset_portfolioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolioID',
            field=models.IntegerField(default=0),
        ),
    ]
