# Generated by Django 2.2.6 on 2019-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='abbreviation',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
